import { LogOut, User, Users } from 'lucide-react'
import type { FirebaseConnectionState } from '../types/game'
import { ConnectionPill } from './ConnectionPill'
import { BrandMark } from './BrandMark'

export interface HeaderProps { operatorId: string; onlineUsers: number | null; connection: FirebaseConnectionState; onLogout: () => void }

export function Header({ operatorId, onlineUsers, connection, onLogout }: HeaderProps) {
  return <header className="border-b border-white/[.07] bg-[#0a1011]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl flex-wrap items-center gap-3 px-3 py-3 sm:px-5"><div className="flex items-center gap-2.5"><BrandMark compact /><div className="leading-tight"><p className="text-sm font-bold tracking-[.13em] text-slate-100">MAGIC SCRIPT</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[.18em] text-emerald-300/70">Game console</p></div></div><div className="ml-auto flex flex-wrap items-center justify-end gap-1.5 sm:gap-2"><span className="hidden items-center gap-2 rounded-full border border-white/[.1] bg-white/[.025] px-3 py-1.5 text-xs text-slate-400 sm:inline-flex"><User className="h-3.5 w-3.5 text-cyan-300" /><span data-testid="operator-id" className="max-w-[130px] truncate font-semibold text-slate-300">{operatorId}</span></span>{onlineUsers !== null && <span className="status-badge border-emerald-300/15 bg-emerald-300/[.05] text-slate-300"><Users className="h-3.5 w-3.5 text-emerald-300" /><span className="hidden sm:inline">Online display</span><span className="status-dot animate-pulse-soft bg-emerald-300" /><span className="mono" data-testid="online-users">{onlineUsers}</span></span>}<ConnectionPill state={connection} /><button type="button" onClick={onLogout} aria-label="Log out" title="Sign out" className="inline-flex h-9 w-9 items-center justify-center rounded-xl border border-white/[.1] bg-white/[.025] text-slate-500 transition hover:border-rose-300/35 hover:text-rose-200"><LogOut className="h-4 w-4" /></button></div></div></header>
}
